#!/usr/bin/env python3
"""Regenerate README.md's version-pinned sections.

Called by .github/workflows/update-readme.yml with these env vars:
  REPO     owner/name (e.g. Aiml3ss/sipario-releases)
  MAC_VER  newest macOS version, no prefix (e.g. 0.43.1)
  WIN_VER  newest Windows version, no prefix (e.g. 0.1.0)
  TV_VER   newest Android TV version, no prefix (e.g. 1.7.7)
  MAC_SHA  sha256 of the latest Sipario-macos.dmg
  WIN_SHA  sha256 of the latest Sipario-windows.msi
  TV_SHA   sha256 of the latest Sipario-TV.apk

Rewrites the three marked regions in README.md:
  <!-- versions:table:begin -->      the Downloads table
  <!-- versions:apk-note:begin -->   the "current APK is ..." sentence
  <!-- versions:checksums:begin -->  the sha256 block

Exits non-zero if a marker is missing, so a hand-edit that drops one fails
the workflow loudly instead of silently leaving stale text behind.
"""

import os
import re
import sys

repo = os.environ["REPO"]
mac_ver = os.environ["MAC_VER"]
win_ver = os.environ["WIN_VER"]
tv_ver = os.environ["TV_VER"]
mac_sha = os.environ["MAC_SHA"]
win_sha = os.environ["WIN_SHA"]
tv_sha = os.environ["TV_SHA"]
base = f"https://github.com/{repo}/releases"

# The download-action links go through sipario.tv/download/{mac,windows,tv}
# (which resolve to these same release assets) so downloads from the repo
# README are counted like every other channel. The Release Notes column keeps
# its GitHub tag link. Do NOT repoint the sipario.tv download routes
# themselves — the TV Downloader code (5358756) and the apps' self-updaters
# depend on them.
table = f"""<!-- versions:table:begin (auto-generated by .github/workflows/update-readme.yml — do not edit by hand) -->
| Platform | Current Download | Version | Release Notes |
|---|---|---|---|
| macOS desktop | [Download the DMG](https://sipario.tv/download/mac) | {mac_ver} | [macos-v{mac_ver}]({base}/tag/macos-v{mac_ver}) |
| Windows desktop **(alpha)** | [Download the MSI](https://sipario.tv/download/windows) | {win_ver} | [windows-v{win_ver}]({base}/tag/windows-v{win_ver}) |
| Android TV | [Download the APK](https://sipario.tv/download/tv) | {tv_ver} | [android-tv-v{tv_ver}]({base}/tag/android-tv-v{tv_ver}) |
<!-- versions:table:end -->"""

apk_note = f"""<!-- versions:apk-note:begin -->
The current APK is version `{tv_ver}`.
<!-- versions:apk-note:end -->"""

checksums = f"""<!-- versions:checksums:begin -->
```text
Sipario-macos.dmg (macos-v{mac_ver})
sha256 {mac_sha}

Sipario-windows.msi (windows-v{win_ver})
sha256 {win_sha}

Sipario-TV.apk (android-tv-v{tv_ver})
sha256 {tv_sha}
```
<!-- versions:checksums:end -->"""

readme = open("README.md").read()
for marker, block in [
    ("table", table),
    ("apk-note", apk_note),
    ("checksums", checksums),
]:
    pattern = re.compile(
        rf"<!-- versions:{marker}:begin[^>]*-->.*?<!-- versions:{marker}:end -->",
        re.S,
    )
    if not pattern.search(readme):
        sys.exit(f"marker versions:{marker} not found in README.md")
    # Lambda replacement so backslash/group semantics in re.sub can never
    # mangle the block content.
    readme = pattern.sub(lambda _m: block, readme, count=1)

open("README.md", "w").write(readme)
print(f"README regenerated for macos-v{mac_ver} / windows-v{win_ver} / android-tv-v{tv_ver}")
